app = "superglue"
primary_region = "ord"

[build]
  dockerfile = "docker/Dockerfile"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service]]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/health"
    protocol = "http"
    port = 3000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
